export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'

export const CALL_POST_REQUEST = "CALL_POST_REQUEST"
export const CALL_POST_FAILURE = "CALL_POST_FAILURE"
export const CALL_POST_SUCCESS = "CALL_POST_SUCCESS"

export const NOTICE_NUM_SETTING = "NOTICE_NUM_SETTING"
export const TRAB_BEST_SETTING = "TRAB_BEST_SETTING"
export const FILTER_ORDERBY_SETTING = "FILTER_ORDERBY_SETTING"

export const ADD_TEMA_LIST = "ADD_TEMA_LIST"
export const REMOVE_TEMA_LIST = "REMOVE_TEMA_LIST"

export const SET_USER_SETTING = "SET_USER_SETTING"
export const USER_LOG_OUT = "USER_LOG_OUT"

export const COUNTRY_ADD = 'COUNTRY_ADD'
export const COUNTRY_REMOVE = 'COUNTRY_REMOVE'

export const SET_INDEX_POSTS = "SET_INDEX_POSTS"
export const SET_INDEX_SELLERS = "SET_INDEX_SELLERS"

export const SET_TARGET_SELLER_DATA = "SET_TARGET_SELLER_DATA"
export const SET_TARGET_SELLER_POSTS = "SET_TARGET_SELLER_POSTS"

export const SET_MORE_INDEX_SELLER = "SET_MORE_INDEX_SELLER"

export const MATCHING_SELLER_DATA_SET = "MATCHING_SELLER_DATA_SET"

export const SET_COUNTRY_LIST = "SET_COUNTRY_LIST"

export const SET_MODAL_LISTS = "SET_MODAL_LISTS"